### ISSUE TITLE
1.0 TODO list

### ISSUE THREAD

**Issue by dy** [web-being/thirdstarstudios#1]
# Sections

* [ ] photogallery
  * [ ] photos @SteveBadMofoLevine 
* [ ] services for musicians
  * [ ] list of services @SteveBadMofoLevine
  * [ ] price range
* [ ] services film/tv/games
  * [ ] list of services @SteveBadMofoLevine 
  * [ ] price range
* [ ] corporate/commercials
  * [ ] list of services @SteveBadMofoLevine 
  * [ ] price range
* [ ] equipment
  * [ ] photos
  * [ ] item names/blurbs @SteveBadMofoLevine 
* [ ] contact
  * [ ] contact details @SteveBadMofoLevine 
* [ ] ? blog
* [ ] about
* [ ] reviews
* [ ] ? FAQ

## Tasks

- [ ] menu on the bottom, feeling of solid foundation
- [ ] pictures eye candy open on the top, make them visible
- [ ] put in icons for services
- [ ] icons for equipment
- [ ]

**Comment by SteveBadMofoLevine** [comment]
## Services:

### Music Services:

In-studio multi-track recording
Live show multi-track recording
Editing
Mixing
Mastering
Original music composition


### Multimedia Services:

Voice-over and ADR recording 
Voice-over talent
Audio engineering and mixing
Original music composition

### Corporate/commercial:

Live event setup and sound
Voice-over recording
Multimedia audio engineering and mixing
Original music/ jingle composition



## Contact:

Steve@ThirdStarStudios.com
(438) 826-6514
Appt 101, 6965 Rue Drolet
Montreal, Quebec
H2S 2T5




## Equipment:

### Preamps:

Neve 1073 DPA
Focusrite ISA828
Universal Audio Apollo (with Unison)

Compressors

Universal Audio 1176

### Converters:

Burl M80 Mothership
Universal Audio Apollo

### DAWs:

Pro Tools HD 12.7
Presonus Studio One 3.5

### Plugins:

Universal Audio
SoundToys
Waves
Celemony
iZotope
Klanghelm
Sknote

**Comment by bvarba** [comment]
Design Guidelines (see above)

**Comment by dfcreative** [comment]
Simple design reference site http://jlord.us/essential-electron/
